spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:mem:testdb # in-memory 주소 설정
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true

client:
  kakao:
    host: https://dapi.kakao.com
    rest-api-key: KakaoAK c25c198ae97858ea1fabe0f4f5909c33
  naver:
    host: https://openapi.naver.com
    client-id: eQTz5HAWuOEQEfUE5pGd
    client-secret: l0QnaYIjHx

api:
  search:
    handler:
      kakao:
        next-handler: NaverSearchHandler
      naver:
        next-handler: FailedToSearchHandler

schedule:
  top10:
    period: 10000 # millisec
